<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>monthsOption</name>
   <tag></tag>
   <elementGuidId>3dc699ba-1138-4291-a88a-30ef6dddec52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uniform-months']//select[@id='months']//option[@value='${months}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='uniform-months']//select[@id='months']//option[@value='${months}']</value>
      <webElementGuid>28003b69-7b75-490a-95a2-3a3fbd063175</webElementGuid>
   </webElementProperties>
</WebElementEntity>
